# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=15)),
            ],
        ),
    ]
