# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=25)),
                ('emp_user', models.CharField(max_length=8)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_pass', models.CharField(max_length=15)),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
