# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=25)),
                ('poster', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_type', models.CharField(max_length=10)),
                ('song_img', models.CharField(max_length=50)),
                ('song_length', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movies')),
            ],
        ),
    ]
